# Heart Sensor
import socket
import random

# Creating a TCP connection with the personal server(PS)
s = socket.socket()
host = socket.gethostname()
port = 40122

# data generated by the Sensor 
num1 = 'HEART :: Systole value: ' + str(random.randint(1,101))
num2 = 'HEART :: Distole value: ' + str(random.randint(109,700))
num3 = 'HEART :: Beats per min: ' + str(random.randint(60,71))

#Connecting with the PS
s.connect((host,port))

#sending and receiving 
s.send(num1)
msg = s.recv(50)
print msg
s.send(num2)
msg = s.recv(50)
print msg
s.send(num3)
msg = s.recv(50)
print msg
s.send("BYE")
#closing connection
s.close()
